export type { Player, Team, PeladaState, TeamIdFactory, DrawOutcome } from "./types";
export { formInitialState } from "./rules/formation";
export { compactQueue } from "./rules/queue";
export { applyResult } from "./rules/match-result";
export { resolveDraw } from "./rules/draw";
export { playerJoins } from "./rules/join";
export { playerLeaves } from "./rules/leave";
export { swapPlayers } from "./rules/swap";
export { shuffle } from "./rules/shuffle";
export { flattenPlayers } from "./rules/flatten";
export { normalizeName, duplicateGroups, hasUnresolvedDuplicates } from "./players";
